boolVal = java.lang.Boolean.TRUE;
hashmap = new java.util.HashMap();
hashmap.put("foo", "hello");
ret = new java.util.HashMap();
ret.put("title", title.toString());
ret.put("boolVal", boolVal);
ret.put("hashmap", hashmap);
ret.put("daString", "Simple String");
errors.add("This is a real problem!");
ret;
