//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.27 at 11:08:05 AM CET 
//


package org.identityconnectors.peoplesoft.compintfc.mapping.idm.jaxbgen;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.identityconnectors.peoplesoft.compintfc.mapping.idm.jaxbgen package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Waveset_QNAME = new QName("", "Waveset");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.identityconnectors.peoplesoft.compintfc.mapping.idm.jaxbgen
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link WavesetType }
     * 
     */
    public WavesetType createWavesetType() {
        return new WavesetType();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link ConfigurationType }
     * 
     */
    public ConfigurationType createConfigurationType() {
        return new ConfigurationType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WavesetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Waveset")
    public JAXBElement<WavesetType> createWaveset(WavesetType value) {
        return new JAXBElement<WavesetType>(_Waveset_QNAME, WavesetType.class, null, value);
    }

}
